# Generated by Django 5.0.4 on 2024-05-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('recipe_name', models.CharField(blank=True, max_length=40, null=True)),
                ('recipe_desc', models.CharField(blank=True, max_length=400, null=True)),
                ('recipe_ingridient', models.CharField(blank=True, max_length=400, null=True)),
                ('dish_image', models.ImageField(blank=True, null=True, upload_to='static/profile_images/')),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('Email_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
