# Generated by Django 5.0.4 on 2024-05-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_recipe',
            name='recipe_instructions',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
