# Generated by Django 5.0.4 on 2024-05-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_maker', '0002_add_recipe_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_recipe',
            name='dish_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
