# Generated by Django 5.0.4 on 2024-05-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_maker', '0003_alter_add_recipe_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_recipe',
            name='dish_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_maker/images/'),
        ),
    ]
